Lesson 5
anna-boeva-mf/tf24java-2 pull request #3
Opened 2024-09-25 15:52 UTC by anna-boeva-mf

2024-09-25 19:56 UTC, lParzivall requested changes

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/GenericRepository.java
> +    private final ConcurrentHashMap<Integer, T> storage = new ConcurrentHashMap<>();
айди можно тоже сделать дженериком, чтобы была возможность его выбирать

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/clients/CategoryApiClient.java
> +    private static final String BASE_URL = "http://localhost:8080/api/v1/places";
вынести в проперти

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/clients/CategoryApiClient.java
> +    private static final String BASE_URL = "http://localhost:8080/api/v1/places";
тут должен быть урл кудаго

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/clients/CategoryApiClient.java
> +    private static final String BASE_URL = "http://localhost:8080/api/v1/places";
https://kudago.com/public-api/v1.4/place-categories/

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/clients/CategoryApiClient.java
> +    private static final String BASE_URL = "http://localhost:8080/api/v1/places";
иначе как ты на старте получаешь данные?

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/clients/CategoryApiClient.java
> +import okhttp3.*;
https://www.javadude.com/posts/20040522-import-on-demand-is-evil/

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/clients/CategoryApiClient.java
> +    public String getCategoryById(int id) throws IOException {
не совсем понял, зачем вызывать самих себя
только для тестирования в Main? это делать не нужно

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/controllers/CategoryController.java
> +        initializeData();
инициализация не должна происходить в контроллере и в его конструкторе тем более
нужно вынести в отдельный класс конфигурации

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/controllers/CategoryController.java
> +        initializeData();
посмотри в эту сторону https://www.baeldung.com/running-setup-logic-on-startup-in-spring

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/controllers/CategoryController.java
> +        initializeData();
мне нравится ApplicationRunner

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/controllers/CategoryController.java
> +    private final GenericRepository<Category> categoryRepository = new GenericRepository<>();
нужно использовать DI
в спринге не создаем объекты через new

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/controllers/CategoryController.java
> +    private static int counter = 1;
что с многопоточкой?)

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/controllers/CategoryController.java
> +        RestTemplate restTemplate = new RestTemplate();
логику запроса по ресту вынести отдельный класс клиент
RestTemplate не должен создаваться через  new

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/controllers/CategoryController.java
> +        return List.copyOf(categoryRepository.findAll());
зачем здесь копия?

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/controllers/CategoryController.java
> +        int Id = genId();
почему с большой буквы?)

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/controllers/LocationController.java
> +public class LocationController {
тут все то же самое

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/logging/LogExecutionTime.java
> +package ru.tbank.logging;
не вынесено в стартер

2024-09-25 19:56 UTC, lParzivall commented on src/main/java/ru/tbank/controllers/LocationController.java
> +        return List.copyOf(locationRepository.findAll());
нет слоя сервиса, в котором будет вызываться репо
нет обработки ошиюок, если не нашли, то какой ответ отдадим(хотим в идеале 404)
посмотреть в сторону exceptionHandler @ControllerAdvice

2024-10-02 07:18 UTC, anna-boeva-mf commented
Метод getCategoryById требуется по условию ДЗ.
Запросы к сервису выполняла с помощью Postman на localhost, тесты напишу в следующей ДЗ.

2024-10-02 14:18 UTC, lParzivall commented on src/main/java/ru/tbank/controllers/CategoryController.java
> +    @LogExecutionTime
зачем над методами, если есть над классом

2024-10-02 14:18 UTC, lParzivall commented on src/main/java/ru/tbank/controllers/CategoryController.java
> +        return this.categoryService.getCategoryById(id);
this не нужен, и так будет работать

2024-11-03 18:50 UTC, merged